name: Deploy to Azure VM using password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy via SSH with Password
      env:
        HOST: ${{ secrets.AZURE_VM_HOST }}
        USER: ${{ secrets.AZURE_VM_USER }}
        PASS: ${{ secrets.AZURE_VM_PASSWORD }}
      run: |
        sshpass -p "$PASS" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          cd employee-management-app
          git pull origin main
          docker compose down
          docker compose up --build -d
        EOF
